### ISSUE TITLE
Not able to hit the endpoints after bringing up the local kruize demo application

### ISSUE THREAD

**Issue by suryaachandra** [kruize/kruize-demos#69]
Hi Team,

I have setup this demo application in my locally and seems the application came up but when I try to hit the endpoints in the logs I get page cannot be displayed . 

![image](https://github.com/kruize/kruize-demos/assets/5617802/67ac9ed6-96c4-4163-abf2-16effb2a2dcb)

one change I have done is changed the MIN_MEM from 16384 to 7128

I am attaching the logs below,  i am not seeing any issue in the logs only I am suspecting is 

**autotune-f44b6c8d4-65rlc               1/2     CrashLoopBackOff   2 (16s ago)     2m45s**

but unable to figure out why it CrashLoop

[Log.txt](https://github.com/kruize/kruize-demos/files/14432198/Log.txt)

Kindly help on this issue

**Comment by suryaachandra** [comment]
when i checked the logs i am getting this error in the log

__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-02-29 07:24:45,445 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': The connection attempt failed.
2024-02-29 07:24:45,446 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (main) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:315)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
        at org.postgresql.Driver.makeConnection(Driver.java:465)
        at org.postgresql.Driver.connect(Driver.java:264)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:204)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:490)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:472)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
        at org.postgresql.core.PGStream.<init>(PGStream.java:95)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
        ... 12 more

2024-02-29 07:24:55,621 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': The connection attempt failed.
2024-02-29 07:24:55,622 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) SQL Error: 0, SQLState: 08001
2024-02-29 07:24:55,623 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (main) The connection attempt failed.
2024-02-29 07:24:55,635 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
        at org.postgresql.core.PGStream.<init>(PGStream.java:95)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
        at org.postgresql.Driver.makeConnection(Driver.java:465)
        at org.postgresql.Driver.connect(Driver.java:264)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:204)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:490)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:472)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by bharathappali** [comment]
@suryaachandra Thanks for trying out Kruize. 

To help you out and better understand the issue I need some details which are mentioned below:

- I'm expecting you were running Kruize on minikube setup on a windows machine, Is my assumption correct?
- Can you please share us the output of `kubectl -n monitoring describe pod <autotune pod name>`
- Can I please know which demo you are trying? is it remote monitoring or local monitoring? 
   (currently only `remote monitoring demo` works as we are working on developing the local monitoring use case)

**Comment by suryaachandra** [comment]
Hi @bharathappali ,

Please find my responses,

1. I'm expecting you were running Kruize on minikube setup on a windows machine, Is my assumption correct? 
 **Yes running on my windows machine**
3. Can you please share us the output of kubectl -n monitoring describe pod <autotune pod name>
Log: 
[Log2.txt](https://github.com/kruize/kruize-demos/files/14445222/Log2.txt)

4. Can I please know which demo you are trying? is it remote monitoring or local monitoring?
**Steps followed for running the demo
1) downloaded the minikube
2) cloned the repo https://github.com/kruize/kruize-demos to local 
3) ran the ./autotune_minikube_demo_setup.sh
**Attaching the output log**
[Log3.txt](https://github.com/kruize/kruize-demos/files/14445272/Log3.txt)
**But after the container came up unable to access the endpoints to view the results**
5. (currently only remote monitoring demo works as we are working on developing the local monitoring use case)
**I was normally executing the above command could you please let me know how to execute remote monitoring demo .**
